mlp_config:
  n_hidden: 2
  hidden_dim: 64
num_iters: 61
epochs_per_iter: 10
steps_per_iter: 2048
batch_size: 128
seed: 0
discount: 0.99
lam: 0.99
eps: 0.2
lr: 3e-4
num_envs: 8
adam_eps: 1e-5
max_grad_norm: 0.5
standardise_advantage: true
ortho_init: true